[package]
name = "authentication_rocket"
version = "0.1.0"
authors = ["Riley Trautman <asonix.dev@gmail.com>"]

[dependencies]
authentication_backend = { path = "../authentication_backend" }
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.8"
serde = "0.9.2"
serde_json = "0.9.2"
serde_derive = "0.9.2"
